export const StudentProfileActionTypes = {
    SET_CURRENT_STUDENTS_PROFILE: 'SET_CURRENT_STUDENTS_PROFILE',
    ADD_STUDENT_TO_LIST: 'ADD_STUDENT_TO_LIST',
    ADD_SEMESTER_TO_STUDENT_LIST: 'ADD_SEMESTER_TO_STUDENT_LIST',
    ADD_MODULE_TO_SEMESTER: 'ADD_MODULE_TO_SEMESTER',
    CHANGE_ATTRIBUTE: 'CHANGE_ATTRIBUTE',
    DELETE_STUDENT: 'DELETE_STUDENT'
};
  